2021-07-11 16:43:47.740 +04:00 [INF] SignInSystemOperations --- GetSignInSystem method started
2021-07-11 16:51:34.869 +04:00 [INF] SignInSystemOperations --- GetSignInSystem method started
2021-07-11 16:51:35.353 +04:00 [ERR] 
OnlineShop.Core.Exceptions.LogicException: Wrong User Id
   at OnlineShop.BLL.Operations.SignInSystemOperation.Get(Int32 id) in D:\Basic It Center\Projects\Online Shop\OnlineShopDB\OnlineShop.BLL\Operations\SignInSystemOperation.cs:line 23
   at OnlineShop.API.Controllers.SignInSystemController.GetId(Int32 id) in D:\Basic It Center\Projects\Online Shop\OnlineShopDB\OnlineShop.API\Controllers\SignInSystemController.cs:line 24
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at OnlineShop.API.Middlewares.ErrorHandlingMiddleware.Invoke(HttpContext context) in D:\Basic It Center\Projects\Online Shop\OnlineShopDB\OnlineShop.API\Middlewares\ErrorHandlingMiddleware.cs:line 25
2021-07-11 16:51:37.883 +04:00 [INF] SignInSystemOperations --- GetSignInSystem method started
2021-07-11 16:51:37.904 +04:00 [INF] SignInSystemOperations --- GetSignInSystem method finished
2021-07-11 16:51:52.087 +04:00 [INF] SignInSystemOperations --- GetSignInSystem method started
2021-07-11 16:51:52.306 +04:00 [ERR] 
OnlineShop.Core.Exceptions.LogicException: Wrong User Id
   at OnlineShop.BLL.Operations.SignInSystemOperation.Get(Int32 id) in D:\Basic It Center\Projects\Online Shop\OnlineShopDB\OnlineShop.BLL\Operations\SignInSystemOperation.cs:line 23
   at OnlineShop.API.Controllers.SignInSystemController.GetId(Int32 id) in D:\Basic It Center\Projects\Online Shop\OnlineShopDB\OnlineShop.API\Controllers\SignInSystemController.cs:line 24
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at OnlineShop.API.Middlewares.ErrorHandlingMiddleware.Invoke(HttpContext context) in D:\Basic It Center\Projects\Online Shop\OnlineShopDB\OnlineShop.API\Middlewares\ErrorHandlingMiddleware.cs:line 25
